CREATE DATABASE RubikCube

USE RubikCube

--CREATE TABLE

CREATE TABLE Users (
	id NVARCHAR(255) NOT NULL PRIMARY KEY,
	name NVARCHAR(255) NOT NULL,
	email NVARCHAR(255) NOT NULL,
	userName NVARCHAR(255) NOT NULL,
	password NVARCHAR(255) NOT NULL
)

CREATE TABLE Algorithms (
	id NVARCHAR(255) NOT NULL PRIMARY KEY,
	algorithm NVARCHAR(255) NOT NULL,
	rubikCubeId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES RubikCubes(id)
)

CREATE TABLE AlgorithmRecords (
	userId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(id),
	algorithmId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Algorithms(id),
	timeCreate smalldatetime NOT NULL,
	record time NOT NULL
)

CREATE TABLE AlgorithmStatuses (
	userId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(id),
	algorithmId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Algorithms(id),
	algorithmStatus INT NOT NULL
)

CREATE TABLE RubikCubes (
	id NVARCHAR(255) NOT NULL PRIMARY KEY,
	faces NVARCHAR(255) NOT NULL
)

CREATE TABLE Categories (
	id NVARCHAR(255) NOT NULL PRIMARY KEY,
	name NVARCHAR(255) NOT NULL
)

CREATE TABLE AlgorithmCategories (
	algorithmId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Algorithms(id),
	categoryId NVARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Categories(id),
)